version: '3'
services:
  manager:
    build: ./manager
    env_file:
      - .env
    volumes:
      - ./manager/app:/app
      - ./manager/data:/data
    ports:
      - 8000:8000

  example-extractor:
    build: ./example-extractor
    env_file:
      - .env
    volumes:
      - ./example-extractor/app:/app

  gmail-extractor:
    build: 
      context: ./gmail-extractor
      args:
          MANAGER_ENDPOINT:   ${MANAGER_ENDPOINT}
          EMAIL_ADDRESS:      ${EMAIL_ADDRESS}
          EMAIL_APP_PASSWORD: ${EMAIL_APP_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./gmail-extractor/app:/app
      - ./gmail-extractor/data:/data

  infodengue-extractor:
    build: 
      context: ./infodengue-extractor
      args:
          MANAGER_ENDPOINT: ${MANAGER_ENDPOINT}
    env_file:
      - .env
    volumes:
      - ./infodengue-extractor/app:/app

  sivep-extractor:
    build: 
      context: ./sivep-extractor
      args:
          MANAGER_ENDPOINT: ${MANAGER_ENDPOINT}
    env_file:
      - .env
    volumes:
      - ./sivep-extractor/app:/app
