services:
  manager:
    build: ./manager
    env_file:
      - .env
    volumes:
      - ./manager/app:/app
      - ./manager/data:/data
    ports:
      - 8214:8000
    networks:
      - default
      - shared-network

  example-extractor:
    build: ./example-extractor
    env_file:
      - .env
    volumes:
      - ./example-extractor/app:/app
    networks:
      - default
      - shared-network

  gmail-extractor:
    build: 
      context: ./gmail-extractor
      args:
          MANAGER_ENDPOINT:   ${MANAGER_ENDPOINT}
          EMAIL_ADDRESS:      ${EMAIL_ADDRESS}
          EMAIL_APP_PASSWORD: ${EMAIL_APP_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./gmail-extractor/app:/app
      - ./gmail-extractor/data:/data
    networks:
      - default
      - shared-network

  infodengue-extractor:
    build: 
      context: ./infodengue-extractor
      args:
          MANAGER_ENDPOINT: ${MANAGER_ENDPOINT}
    env_file:
      - .env
    volumes:
      - ./infodengue-extractor/app:/app
    networks:
      - default
      - shared-network

  sivep-extractor:
    build: 
      context: ./sivep-extractor
      args:
          MANAGER_ENDPOINT: ${MANAGER_ENDPOINT}
    env_file:
      - .env
    volumes:
      - ./sivep-extractor/app:/app
    networks:
      - default
      - shared-network

  monit-collector:
    build:
      context: ./monit-collector
      args:
          MANAGER_ENDPOINT: ${MANAGER_ENDPOINT}
    env_file:
      - .env
    volumes:
      - ./monit-collector/app:/app
      - ./monit-collector/data:/data
    ports:
      - 8215:8000
    networks:
      - default
      - shared-network

networks:
  shared-network:
    external: true
