version: '3'
services:
  manager:
    build: ./manager
    volumes:
      - ./manager/app:/app
      - ./manager/data:/data
    ports:
      - 8000:8000

  gmail-extractor:
    build: ./gmail-extractor 
    volumes:
      - ./gmail-extractor/app:/app
      - ./gmail-extractor/data:/data